# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /src

# Copy package.json and package-lock.json to the working directory
COPY . .

# Install the dependencies
RUN npm install

# Expose the port on which the server will run
EXPOSE 3000

# Start the server
CMD ["npm", "start"]

